### ISSUE TITLE
点击显示服务拓扑后报错

### ISSUE THREAD

**Issue by liuchengfei1982** [Nepxion/Docs#1]
你好。我在本地部署了你的项目并启动了ConsoleLauncher.java。同时我也启动了我的demo微服务，代码来自于<重新定义spring cloud>，代码地址
https://github.com/SpringCloud/spring-cloud-code/tree/master/ch21-1

然后点击菜单’显示服务拓扑‘报错。报错如下，求指点下问题出在哪里，谢谢
java.lang.IllegalArgumentException: {"timestamp":"2018-12-03T04:53:54.241+0000","status":404,"error":"Not Found","message":"No message available","path":"/console/groups"}
	at com.nepxion.discovery.common.util.RestUtil.fromJson(RestUtil.java:26)
	at com.nepxion.discovery.console.desktop.controller.ServiceController.getGroups(ServiceController.java:72)
	at com.nepxion.discovery.console.desktop.workspace.ServiceTopology$3.execute(ServiceTopology.java:546)
	at com.nepxion.swing.action.JSecurityAction.actionPerformed(JSecurityAction.java:150)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by zypabc1234** [comment]
> 你好。我在本地部署了你的项目并启动了ConsoleLauncher.java。同时我也启动了我的demo微服务，代码来自于<重新定义spring cloud>，代码地址
> https://github.com/SpringCloud/spring-cloud-code/tree/master/ch21-1
> 
> 然后点击菜单’显示服务拓扑‘报错。报错如下，求指点下问题出在哪里，谢谢
> java.lang.IllegalArgumentException: {"timestamp":"2018-12-03T04:53:54.241+0000","status":404,"error":"Not Found","message":"No message available","path":"/console/groups"}
> at com.nepxion.discovery.common.util.RestUtil.fromJson(RestUtil.java:26)
> at com.nepxion.discovery.console.desktop.controller.ServiceController.getGroups(ServiceController.java:72)
> at com.nepxion.discovery.console.desktop.workspace.ServiceTopology$3.execute(ServiceTopology.java:546)
> at com.nepxion.swing.action.JSecurityAction.actionPerformed(JSecurityAction.java:150)
> at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
> at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
> at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
> at java.awt.Component.processMouseEvent(Component.java:6535)
> at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
> at java.awt.Component.processEvent(Component.java:6300)
> at java.awt.Container.processEvent(Container.java:2236)
> at java.awt.Component.dispatchEventImpl(Component.java:4891)
> at java.awt.Container.dispatchEventImpl(Container.java:2294)
> at java.awt.Component.dispatchEvent(Component.java:4713)
> at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
> at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
> at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
> at java.awt.Container.dispatchEventImpl(Container.java:2280)
> at java.awt.Window.dispatchEventImpl(Window.java:2750)
> at java.awt.Component.dispatchEvent(Component.java:4713)
> at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
> at java.awt.EventQueue.access$500(EventQueue.java:97)
> at java.awt.EventQueue$3.run(EventQueue.java:709)
> at java.awt.EventQueue$3.run(EventQueue.java:703)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
> at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> at java.awt.EventQueue$4.run(EventQueue.java:731)
> at java.awt.EventQueue$4.run(EventQueue.java:729)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
> at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
> at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

你用户名和密码填的什么

**Comment by HaojunRen** [comment]
你那个是很老的代码，请到我Github网站去拿最新代码，用户名密码admin

**Comment by zypabc1234** [comment]
> 你那个是很老的代码，请到我Github网站去拿最新代码，用户名密码admin

用的是您这最新的代码的用户名密码admin  提示用户名或密码错误

**Comment by zypabc1234** [comment]
> > 你那个是很老的代码，请到我Github网站去拿最新代码，用户名密码admin
> 
> 用的是您这最新的代码的用户名密码admin 提示用户名或密码错误

![image](https://user-images.githubusercontent.com/31096686/53712381-96031b00-3e81-11e9-996e-91a42209dd6a.png)

**Comment by Wang-Ray** [comment]
《重新定义spring cloud》对应的版本是4.2.1，建议discovery-console-desktop使用4.2.1的版本。

**Comment by HaojunRen** [comment]
现在已经是4.8.6版本了
